import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'English' | 'Hindi' | 'Marathi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  English: {
    'hero.title': "India's Most Efficient & Smart Egg Incubator.",
    'hero.tagline': "Bridging the gap with smart,\nprecision hatching technology.",
    'hero.cta': "Pre-order Now & Save 20%",
    'hero.capacity': "Capacity Options",
    'hero.eggs': "Eggs",
    'hero.preorder': "Pre-orders open",
    'hero.incubated': "Incubated at AIC Mahindra | Startup India Certified",
    'hero.tags': "Made for Farmers,Innovative,Plug and Play,Built to Scale",
    'nav.technology': "Technology",
    'nav.metrics': "Metrics",
    'nav.gallery': "Gallery",
    'nav.getStarted': "Get Started",
    'footer.partner': "Partnered with",
    'footer.devBy': "Developed by",
    'footer.desc': "Pioneering automated precision for the future of sustainable poultry farming in rural and semi-urban ecosystems.",
    'footer.partners': "Partners",
    'footer.incubation': "Incubation Centre",
    'footer.contact': "Contact",
    'footer.rights': "All rights reserved.",
    'section.problem.title': "Stop Losing Money on 'Poor Hatching Rates'",
    'section.problem.desc': "Modern cultivation faces extreme volatility. Traditional incubation methods lack the precision required for institutional scale, leading to unpredictable yields and resource waste.",
    'section.solution.title': "One Single Breakthrough Solution",
    'section.solution.desc': "Our AI-powered Smart Incubator eliminates every obstacle in your hatching journey. From thermal stability to automated humidity, we've solved it all in one plug-and-play system.",
    'section.solution.feat1.title': "Thermal Perfection",
    'section.solution.feat1.desc': "Active feedback loops maintaining 0.01°C accuracy, solving unpredictable climate shifts.",
    'section.solution.feat2.title': "Zero Manual Effort",
    'section.solution.feat2.desc': "Automated egg turning and humidity control, eliminating the need for constant monitoring.",
    'section.solution.feat3.title': "Maximum Yield",
    'section.solution.feat3.desc': "Engineered to achieve a 90% hatch rate, turning every egg into a profit opportunity.",
    'section.how.title': "Plug and Play Simplicity",
    'section.how.subtitle': "Deploy industrial precision in three simple steps.",
    'section.how.step1': "Deploy",
    'section.how.step1.desc': "Rapid installation with modular components that snap together effortlessly.",
    'section.how.step2': "Calibrate",
    'section.how.step2.desc': "Automated systems sense your environment and optimize thermal profiles.",
    'section.how.step3': "Yield",
    'section.how.step3.desc': "Experience consistent, high-percentage outcomes batch after batch.",
    'section.infra.title': "Scalable Infrastructure",
    'section.infra.subtitle': "Professional-grade capacity options for every scale of operation.",
    'section.infra.120.title': "जीone Series 120",
    'section.infra.120.desc': "Precision control for specialized breeders. Achieved 90% Hatch Rate.",
    'section.infra.200.title': "जीone Series 200",
    'section.infra.200.desc': "The standard for mid-sized institutional operations. High efficiency and guaranteed 90% yield.",
    'section.infra.500.title': "जीone Series 500",
    'section.infra.500.desc': "Commercial-scale deployment for large poultry farms and institutions.",
    'section.infra.inquiry': "Inquiry Only",
    'section.trust.title': "Why Trust Serefy Innovations",
    'section.trust.feat1.title': "Precision Engineering",
    'section.trust.feat1.desc': "Aerospace-grade sensors and custom-molded thermal chambers for zero variance.",
    'section.trust.feat2.title': "Data-Driven Thermal Mgmt",
    'section.trust.feat2.desc': "Active feedback loops maintaining 0.01°C accuracy across the entire unit.",
    'section.trust.feat3.title': "Institutional Standards",
    'section.trust.feat3.desc': "Built to exceed international biosecurity and structural durability standards.",
    'section.team.title': "Our Leadership & Partners",
    'section.team.vidhya.title': "Founder & CEO",
    'section.team.vidhya.desc': "Leading the strategic vision and biological research for SERE. Vidhya's focus on incubation physics has been the cornerstone of our hardware development.",
    'section.team.aditya.title': "Co-Founder & CTO",
    'section.team.aditya.desc': "Driving the technological stack and software architecture. Aditya specializes in IoT integration and predictive analytics for agricultural hardware.",
    'section.team.supported': "Supported By",
    'section.seretalks.title': "SereTalks",
    'section.seretalks.subtitle': "Insights and updates from our journey",
    'section.gallery.title': "On the Ground",
    'section.gallery.subtitle': "Real deployments, real impact.",
    'section.gallery.img1': "Vidhya connecting with local farmers in the field",
    'section.gallery.img2': "Poultry farm setup",
    'section.gallery.img3': "Team discussing hardware",
    'section.gallery.img4': "Technology deployment",
    'slides.1.title': "Climate Volatility",
    'slides.1.desc': "External fluctuations disrupting delicate biological environments.",
    'slides.2.title': "Data Blindspots",
    'slides.2.desc': "Inability to track and react to micro-thermal shifts in real-time.",
    'slides.3.title': "Resource Waste",
    'slides.3.desc': "Traditional methods leading to unpredictable yields and lost revenue.",
    'section.interest.title': "Register Interest",
    'section.interest.desc': "Secure your position in our next deployment cycle.",
    'form.firstName': "First Name",
    'form.lastName': "Last Name",
    'form.email': "Email Address",
    'form.phone': "Phone / WhatsApp",
    'form.city': "City / Location",
    'form.role': "I am a...",
    'form.message': "Message (Optional)",
    'form.submit': "Submit Interest",
    'form.consent': "I agree to be contacted by the Serefy Innovations team.",
    'tech.title': "Institutional-Grade Hardware",
    'tech.desc': "Precision-engineered for reliability and scale.",
    'tech.hero.badge': "THE ILLUMINATED LABORATORY",
    'tech.hero.title': "Bridging Tradition & Precision",
    'tech.hero.desc': "We are reimagining the heartbeat of small-scale farming through surgical technology and empathetic design.",
    'tech.hero.cta': "Explore Technology",
    'tech.mission.badge': "Our Mission",
    'tech.mission.title': "Organic Precision",
    'tech.mission.desc': "Agricultural technology often leaves small-scale farmers behind. We believe that innovation shouldn't be reserved for industrial giants.",
    'metrics.title': "Precision Poultry ROI.",
    'metrics.desc': "Experience the shift from traditional guesswork to automated precision.",
    'metrics.compare.title': "Market Comparison",
    'metrics.roi.title': "ROI Intelligence",
    'contact.title': "Let's Talk Precision.",
    'contact.desc': "Whether you're ready to upgrade your hatchery or just have questions about our technology, our team is here to help.",
    'contact.form.title': "Send a Message",
    'contact.form.submit': "Send Message",
    'contact.form.sending': "Sending...",
    'contact.success.title': "Message Sent!",
    'contact.success.desc': "Thank you for reaching out. Our team will get back to you within 24 hours.",
    'wizard.step': "Step",
    'wizard.of': "of",
    'wizard.back': "Back",
    'wizard.next': "Next",
    'wizard.submit': "Submit",
    'wizard.submitting': "Submitting...",
    'wizard.step1.title': "How do you identify?",
    'wizard.step1.desc': "Help us tailor the experience for you.",
    'wizard.role.farmer': "Farmer",
    'wizard.role.farmer.desc': "Individual or small-scale grower",
    'wizard.role.hobbyist': "Hobbyist",
    'wizard.role.hobbyist.desc': "Enthusiast or researcher",
    'wizard.role.investor': "Investor / Institution",
    'wizard.role.investor.desc': "Commercial scale or funding",
    'wizard.step2.capacity.title': "What capacity do you need?",
    'wizard.step2.capacity.desc': "Select the hardware scale that fits your goals.",
    'wizard.step2.partnership.title': "What kind of partnership?",
    'wizard.step2.partnership.desc': "Select the area best aligned with your goals.",
    'wizard.partnership.strategic': "Strategic Investment",
    'wizard.partnership.reseller': "Distribution / Reseller",
    'wizard.partnership.institutional': "Institutional Buyer",
    'wizard.partnership.other': "Other Partnership",
    'wizard.step3.goal.title': "What is your primary goal?",
    'wizard.step3.goal.desc': "Help us understand how we can help you succeed.",
    'wizard.goal.hatch-rate': "Improve hatch rate",
    'wizard.goal.scale': "Scale up operations",
    'wizard.goal.research': "Research / Specialty birds",
    'wizard.goal.first-time': "First time hatching",
    'wizard.step3.timeline.title': "What is your timeline?",
    'wizard.step3.timeline.desc': "When are you looking to move forward?",
    'wizard.timeline.immediate': "Immediate (0-3 months)",
    'wizard.timeline.short': "Short-term (3-6 months)",
    'wizard.timeline.exploring': "Just exploring options for now",
    'wizard.step4.title': "Any specific requirements?",
    'wizard.step4.desc': "Feel free to add any own details or questions (Optional).",
    'wizard.step4.placeholder.investor': "We are looking for...",
    'wizard.step4.placeholder.farmer': "I currently use a different model...",
    'wizard.step5.title': "Final Details",
    'wizard.step5.desc': "Where should we send the confirmation?",
    'thanks.title': "Thank you,",
    'thanks.desc': "Your interest has been officially registered. Our team will be reaching out to you shortly to discuss your pre-order and next steps.",
    'thanks.cta': "Return to Site",
    'legal.terms.title': "Terms and Conditions",
    'legal.terms.content': "By accessing this website, we assume you accept these terms and conditions. Do not continue to use Serefy Innovations if you do not agree to take all of the terms and conditions stated on this page.",
    'legal.privacy.title': "Privacy Policy",
    'legal.privacy.content': "At Serefy Innovations, accessible from our website, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by us and how we use it.",
    'legal.disclaimer.title': "Disclaimer",
    'legal.disclaimer.content': "All the information on this website - Serefy Innovations - is published in good faith and for general information purpose only."
  },
  Hindi: {
    'hero.title': "भारत का सबसे कुशल और स्मार्ट अंडा इनक्यूबेटर।",
    'hero.tagline': "किसानों और तकनीक के बीच की दूरी को कम करना। ग्रामीण उद्यमियों और छोटे पोल्ट्री किसानों के लिए निर्मित।",
    'hero.cta': "अभी प्री-ऑर्डर करें और 20% बचाएं",
    'hero.capacity': "क्षमता विकल्प",
    'hero.eggs': "अंडे",
    'hero.preorder': "प्री-ऑर्डर शुरू",
    'hero.incubated': "AIC महिंद्रा में इनक्यूबेटेड | स्टार्टअप इंडिया प्रमाणित",
    'hero.tags': "किसानों के लिए,नवाचारी,प्लग एंड प्ले,स्केलेबल",
    'nav.technology': "तकनीक",
    'nav.metrics': "मेट्रिक्स",
    'nav.gallery': "गैलरी",
    'nav.getStarted': "शुरू करें",
    'footer.partner': "पार्टनर",
    'footer.devBy': "द्वारा विकसित",
    'footer.desc': "ग्रामीण और अर्ध-शहरी पारिस्थितिकी प्रणालियों में टिकाऊ कुक्कुट पालन के भविष्य के लिए अग्रणी स्वचालित सटीकता।",
    'footer.partners': "भागीदार",
    'footer.incubation': "इनक्यूबेशन सेंटर",
    'footer.contact': "संपर्क",
    'footer.rights': "सर्वाधिकार सुरक्षित।",
    'section.problem.title': "खराब हैचिंग दर पर पैसे खोना बंद करें",
    'section.problem.desc': "आधुनिक खेती को अत्यधिक अस्थिरता का सामना करना पड़ता है। पारंपरिक हैचिंग विधियों में संस्थागत पैमाने के लिए आवश्यक सटीकता की कमी होती है।",
    'section.solution.title': "एक ही क्रांतिकारी समाधान",
    'section.solution.desc': "हमारा AI-संचालित स्मार्ट इनक्यूबेटर आपकी हैचिंग यात्रा की हर बाधा को दूर करता है। थर्मल स्थिरता से लेकर स्वचालित आर्द्रता तक, हमने सब कुछ एक ही सिस्टम में हल कर दिया है।",
    'section.solution.feat1.title': "थर्मल पूर्णता",
    'section.solution.feat1.desc': "0.01°C सटीकता बनाए रखने वाले सक्रिय फीडबैक लूप, अप्रत्याशित जलवायु परिवर्तन को हल करते हैं।",
    'section.solution.feat2.title': "शून्य मैनुअल प्रयास",
    'section.solution.feat2.desc': "स्वचालित अंडा मोड़ना और आर्द्रता नियंत्रण, निरंतर निगरानी की आवश्यकता को समाप्त करता है।",
    'section.solution.feat3.title': "अधिकतम उपज",
    'section.solution.feat3.desc': "90% हैच दर प्राप्त करने के लिए इंजीनियर किया गया, हर अंडे को लाभ में बदल देता है।",
    'section.how.title': "प्लग एंड प्ले सरलता",
    'section.how.subtitle': "तीन सरल चरणों में औद्योगिक सटीकता तैनात करें।",
    'section.how.step1': "तैनात करें",
    'section.how.step1.desc': "मॉड्यूलर घटकों के साथ त्वरित स्थापना जो आसानी से एक साथ जुड़ जाते हैं।",
    'section.how.step2': "कैलिब्रेट करें",
    'section.how.step2.desc': "स्वचालित सिस्टम आपके पर्यावरण को समझते हैं और थर्मल प्रोफाइल को अनुकूलित करते हैं।",
    'section.how.step3': "उपज प्राप्त करें",
    'section.how.step3.desc': "हर बैच के साथ लगातार, उच्च प्रतिशत परिणामों का अनुभव करें।",
    'section.infra.title': "स्केलेबल इंफ्रास्ट्रक्चर",
    'section.infra.subtitle': "हर स्तर के संचालन के लिए पेशेवर-ग्रेड क्षमता विकल्प।",
    'section.infra.120.title': "जीone सीरीज 120",
    'section.infra.120.desc': "विशेषज्ञ प्रजनकों के लिए सटीक नियंत्रण। 90% हैच दर प्राप्त की।",
    'section.infra.200.title': "जीone सीरीज 200",
    'section.infra.200.desc': "मध्यम आकार के संस्थागत संचालन के लिए मानक। उच्च दक्षता और गारंटीकृत 90% उपज।",
    'section.infra.500.title': "जीone सीरीज 500",
    'section.infra.500.desc': "बड़े पोल्ट्री फार्मों और संस्थानों के लिए वाणिज्यिक स्तर की तैनाती।",
    'section.infra.inquiry': "केवल पूछताछ",
    'section.trust.title': "सेरेफी इनोवेशन पर भरोसा क्यों करें",
    'section.trust.feat1.title': "सटीक इंजीनियरिंग",
    'section.trust.feat1.desc': "एयरोस्पेस-ग्रेड सेंसर और जीरो वेरिएंस के लिए कस्टम-मोल्डेड थर्मल चैंबर।",
    'section.trust.feat2.title': "डेटा-संचालित थर्मल प्रबंधन",
    'section.trust.feat2.desc': "पूरी इकाई में 0.01°C सटीकता बनाए रखने वाले सक्रिय फीडबैक लूप।",
    'section.trust.feat3.title': "संस्थागत मानक",
    'section.trust.feat3.desc': "अंतरराष्ट्रीय बायोसेक्युरिटी और संरचनात्मक स्थायित्व मानकों से अधिक के लिए निर्मित।",
    'section.team.title': "हमारा नेतृत्व और सहयोगी",
    'section.team.vidhya.title': "संस्थापक और सीईओ",
    'section.team.vidhya.desc': "सेरे के लिए रणनीतिक दृष्टि और जैविक अनुसंधान का नेतृत्व। विद्या का इनक्यूबेशन भौतिकी पर ध्यान हमारे हार्डवेयर विकास का आधार रहा है।",
    'section.team.aditya.title': "सह-संस्थापक और सीटीओ",
    'section.team.aditya.desc': "तकनीकी स्टैक और सॉफ्टवेयर आर्किटेक्चर का संचालन। आदित्य कृषि हार्डवेयर के लिए IoT एकीकरण में माहिर हैं।",
    'section.team.supported': "सहयोग",
    'section.seretalks.title': "सेरे टॉक्स",
    'section.seretalks.subtitle': "हमारी यात्रा से अंतर्दृष्टि और अपडेट",
    'section.gallery.title': "ज़मीनी हकीकत",
    'section.gallery.subtitle': "वास्तविक तैनाती, वास्तविक प्रभाव।",
    'section.gallery.img1': "खेत में स्थानीय किसानों के साथ जुड़ती विद्या",
    'section.gallery.img2': "पोल्ट्री फार्म सेटअप",
    'section.gallery.img3': "हार्डवेयर पर चर्चा करती टीम",
    'section.gallery.img4': "तकनीक की तैनाती",
    'slides.1.title': "जलवायु अस्थिरता",
    'slides.1.desc': "नाजुक जैविक वातावरण को बाधित करने वाले बाहरी उतार-चढ़ाव।",
    'slides.2.title': "डेटा ब्लाइंडस्पॉट्स",
    'slides.2.desc': "रीयल-टाइम में सूक्ष्म-थर्मल बदलावों को ट्रैक करने और प्रतिक्रिया देने में असमर्थता।",
    'slides.3.title': "संसाधन बर्बादी",
    'slides.3.desc': "पारंपरिक तरीके जिससे अप्रत्याशित उपज और राजस्व की हानि होती है।",
    'section.interest.title': "रुचि दर्ज करें",
    'section.interest.desc': "अगले चक्र में अपनी जगह सुरक्षित करें।",
    'form.firstName': "पहला नाम",
    'form.lastName': "अंतिम नाम",
    'form.email': "ईमेल पता",
    'form.phone': "फोन / व्हाट्सएप",
    'form.city': "शहर / स्थान",
    'form.role': "मैं एक...",
    'form.message': "संदेश (वैकल्पिक)",
    'form.submit': "रुचि दर्ज करें",
    'form.consent': "मैं सेरेफी टीम द्वारा संपर्क किए जाने के लिए सहमत हूं।",
    'tech.title': "संस्थागत-ग्रेड हार्डवेयर",
    'tech.desc': "विश्वसनीयता और पैमाने के लिए सटीक-इंजीनियर।",
    'tech.hero.badge': "प्रकाशित प्रयोगशाला",
    'tech.hero.title': "परंपरा और सटीकता का मिलन",
    'tech.hero.desc': "हम सर्जिकल तकनीक और सहानुभूतिपूर्ण डिजाइन के माध्यम से छोटे पैमाने की खेती की कल्पना कर रहे हैं।",
    'tech.hero.cta': "तकनीक का अन्वेषण करें",
    'tech.mission.badge': "हमारा मिशन",
    'tech.mission.title': "जैविक सटीकता",
    'tech.mission.desc': "कृषि तकनीक अक्सर छोटे पैमाने के किसानों को पीछे छोड़ देती है। हमारा मानना है कि नवाचार केवल औद्योगिक दिग्गजों के लिए आरक्षित नहीं होना चाहिए।",
    'metrics.title': "सटीक पोल्ट्री ROI।",
    'metrics.desc': "पारंपरिक अनुमान से स्वचालित सटीकता की ओर बदलाव का अनुभव करें।",
    'metrics.compare.title': "बाजार तुलना",
    'metrics.roi.title': "ROI इंटेलिजेंस",
    'contact.title': "सटीकता की बात करते हैं।",
    'contact.desc': "चाहे आप अपनी हैचरी को अपग्रेड करने के लिए तैयार हों या हमारी तकनीक के बारे में सवाल हों, हमारी टीम यहाँ मदद के लिए है।",
    'contact.form.title': "संदेश भेजें",
    'contact.form.submit': "संदेश भेजें",
    'contact.form.sending': "भेज रहे हैं...",
    'contact.success.title': "संदेश भेजा गया!",
    'contact.success.desc': "संपर्क करने के लिए धन्यवाद। हमारी टीम 24 घंटों के भीतर आपसे संपर्क करेगी।",
    'wizard.step': "चरण",
    'wizard.of': "का",
    'wizard.back': "पीछे",
    'wizard.next': "अगला",
    'wizard.submit': "जमा करें",
    'wizard.submitting': "जमा हो रहा है...",
    'wizard.step1.title': "आपकी पहचान क्या है?",
    'wizard.step1.desc': "अनुभव को आपके लिए अनुकूलित करने में हमारी सहायता करें।",
    'wizard.role.farmer': "किसान",
    'wizard.role.farmer.desc': "व्यक्तिगत या छोटे पैमाने के उत्पादक",
    'wizard.role.hobbyist': "शौकिया",
    'wizard.role.hobbyist.desc': "उत्साही या शोधकर्ता",
    'wizard.role.investor': "निवेशक / संस्थान",
    'wizard.role.investor.desc': "वाणिज्यिक स्तर या वित्त पोषण",
    'wizard.step2.capacity.title': "आपको कितनी क्षमता की आवश्यकता है?",
    'wizard.step2.capacity.desc': "अपने लक्ष्यों के अनुरूप हार्डवेयर स्केल चुनें।",
    'wizard.step2.partnership.title': "किस तरह की साझेदारी?",
    'wizard.step2.partnership.desc': "अपने लक्ष्यों के साथ सर्वोत्तम संरेखित क्षेत्र चुनें।",
    'wizard.partnership.strategic': "रणनीतिक निवेश",
    'wizard.partnership.reseller': "वितरण / पुनर्विक्रेता",
    'wizard.partnership.institutional': "संस्थागत खरीदार",
    'wizard.partnership.other': "अन्य साझेदारी",
    'wizard.step3.goal.title': "आपका प्राथमिक लक्ष्य क्या है?",
    'wizard.step3.goal.desc': "हमें यह समझने में सहायता करें कि हम आपकी सफलता में कैसे मदद कर सकते हैं।",
    'wizard.goal.hatch-rate': "हैच दर में सुधार",
    'wizard.goal.scale': "संचालन का विस्तार",
    'wizard.goal.research': "अनुसंधान / विशेष पक्षी",
    'wizard.goal.first-time': "पहली बार हैचिंग",
    'wizard.step3.timeline.title': "आपकी समयरेखा क्या है?",
    'wizard.step3.timeline.desc': "आप कब आगे बढ़ने की सोच रहे हैं?",
    'wizard.timeline.immediate': "तत्काल (0-3 महीने)",
    'wizard.timeline.short': "अल्पकालिक (3-6 महीने)",
    'wizard.timeline.exploring': "अभी सिर्फ विकल्पों की तलाश",
    'wizard.step4.title': "कोई विशिष्ट आवश्यकताएं?",
    'wizard.step4.desc': "कोई भी विवरण या प्रश्न जोड़ने के लिए स्वतंत्र महसूस करें (वैकल्पिक)।",
    'wizard.step4.placeholder.investor': "हम तलाश रहे हैं...",
    'wizard.step4.placeholder.farmer': "मैं वर्तमान में एक अलग मॉडल का उपयोग करता हूं...",
    'wizard.step5.title': "अंतिम विवरण",
    'wizard.step5.desc': "हमें पुष्टि कहाँ भेजनी चाहिए?",
    'thanks.title': "धन्यवाद,",
    'thanks.desc': "आपकी रुचि आधिकारिक रूप से दर्ज कर ली गई है। हमारी टीम आपके प्री-ऑर्डर और अगले चरणों पर चर्चा करने के लिए जल्द ही आपसे संपर्क करेगी।",
    'thanks.cta': "साइट पर वापस जाएं",
    'legal.terms.title': "नियम और शर्तें",
    'legal.terms.content': "इस वेबसाइट तक पहुँच कर, हम यह मान लेते हैं कि आप इन नियमों और शर्तों को स्वीकार करते हैं। यदि आप इस पृष्ठ पर बताए गए सभी नियमों और शर्तों को मानने से सहमत नहीं हैं तो सेरेफी इनोवेशन का उपयोग करना जारी न रखें।",
    'legal.privacy.title': "गोपनीयता नीति",
    'legal.privacy.content': "सेरेफी इनोवेशन में, हमारी वेबसाइट से सुलभ, हमारी मुख्य प्राथमिकताओं में से एक हमारे आगंतुकों की गोपनीयता है। इस गोपनीयता नीति दस्तावेज़ में हमारे द्वारा एकत्र और रिकॉर्ड की गई जानकारी के प्रकार और हम इसका उपयोग कैसे करते हैं, शामिल है।",
    'legal.disclaimer.title': "अस्वीकरण",
    'legal.disclaimer.content': "इस वेबसाइट - सेरेफी इनोवेशन - पर सभी जानकारी नेक नियति और केवल सामान्य जानकारी के उद्देश्य से प्रकाशित की गई है।"
  },
  Marathi: {
    'hero.title': "भारतातील सर्वात कार्यक्षम आणि स्मार्ट अंडी इनक्यूबेटर.",
    'hero.tagline': "शेतकरी आणि तंत्रज्ञान यांच्यातील दरी कमी करणे. ग्रामीण उद्योजक आणि लहान कुक्कुटपालन शेतकऱ्यांसाठी तयार केलेले.",
    'hero.cta': "आता प्री-ऑर्डर करा आणि 20% वाचवा",
    'hero.capacity': "क्षमता पर्याय",
    'hero.eggs': "अंडी",
    'hero.preorder': "प्री-ऑर्डर सुरू",
    'hero.incubated': "AIC महिंद्रा मध्ये इनक्यूबेटेड | स्टार्टअप इंडिया प्रमाणित",
    'hero.tags': "शेतकऱ्यांसाठी,नाविन्यपूर्ण,प्लग अँड प्ले,स्केलेबल",
    'nav.technology': "तंत्रज्ञान",
    'nav.metrics': "मेट्रिक्स",
    'nav.gallery': "गॅलरी",
    'nav.getStarted': "सुरू करा",
    'footer.partner': "सहभागी",
    'footer.devBy': "द्वारे विकसित",
    'footer.desc': "ग्रामीण आणि निमशहरी भागात शाश्वत कुक्कुटपालनाच्या भविष्यासाठी स्वयंचलित अचूकता विकसित करत आहोत.",
    'footer.partners': "भागीदार",
    'footer.incubation': "इनक्यूबेशन सेंटर",
    'footer.contact': "संपर्क",
    'footer.rights': "सर्व हक्क राखीव.",
    'section.problem.title': "कमी हॅचिंग रेटमुळे होणारे नुकसान थांबवा",
    'section.problem.desc': "पारंपारिक हॅचिंग पद्धतींमध्ये अचूकतेचा अभाव असतो, ज्यामुळे उत्पादनात अनिश्चितता निर्माण होते.",
    'section.solution.title': "एकच क्रांतिकारी उपाय",
    'section.solution.desc': "आमचे AI-आधारित स्मार्ट इनक्यूबेटर तुमच्या हॅचिंग प्रवासातील सर्व अडथळे दूर करते. थर्मल स्थिरतेपासून स्वयंचलित आर्द्रतेपर्यंत, आम्ही सर्व एकाच सिस्टिममध्ये सोडवले आहे.",
    'section.solution.feat1.title': "थर्मल अचूकता",
    'section.solution.feat1.desc': "0.01°C अचूकता राखणारे सक्रिय फीडबॅक लूप, हवामानातील बदल हाताळतात.",
    'section.solution.feat2.title': "शून्य मानवी प्रयत्न",
    'section.solution.feat2.desc': "स्वयंचलित अंडी फिरवणे आणि आर्द्रता नियंत्रण, सतत देखरेखीची गरज संपवते.",
    'section.solution.feat3.title': "जास्तीत जास्त उत्पादन",
    'section.solution.feat3.desc': "90% हॅच रेट मिळवण्यासाठी डिझाइन केलेले, प्रत्येक अंडी नफ्यात बदलते.",
    'section.how.title': "प्लग अँड प्ले सुलभता",
    'section.how.subtitle': "तीन सोप्या चरणांमध्ये औद्योगिक अचूकता तैनात करा.",
    'section.how.step1': "सुरू करा",
    'section.how.step1.desc': "सहजपणे एकत्र जोडल्या जाणाऱ्या घटकांसह जलद स्थापना.",
    'section.how.step2': "तपासा",
    'section.how.step2.desc': "स्वयंचलित प्रणाली तुमचे वातावरण समजून घेतात आणि थर्मल प्रोफाइल सुधारतात.",
    'section.how.step3': "उत्पादन घ्या",
    'section.how.step3.desc': "प्रत्येक बॅचसह सातत्यपूर्ण, उच्च टक्केवारी निकालांचा अनुभव घ्या.",
    'section.infra.title': "स्केलेबल पायाभूत सुविधा",
    'section.infra.subtitle': "प्रत्येक स्तरावरील ऑपरेशन्ससाठी व्यावसायिक-ग्रेड क्षमता पर्याय.",
    'section.infra.120.title': "जीone सिरीज 120",
    'section.infra.120.desc': "विशेष पैदासकारांसाठी अचूक नियंत्रण. 90% हॅच रेट प्राप्त केला.",
    'section.infra.200.title': "जीone सिरीज 200",
    'section.infra.200.desc': "मध्यम आकाराच्या संस्थात्मक ऑपरेशन्ससाठी मानक. उच्च कार्यक्षमता आणि हमी दिलेले 90% उत्पादन.",
    'section.infra.500.title': "जीone सिरीज 500",
    'section.infra.500.desc': "मोठ्या कुक्कुटपालन फार्म आणि संस्थांसाठी व्यावसायिक स्तरावरील तैनाती.",
    'section.infra.inquiry': "केवळ चौकशी",
    'section.trust.title': "सेरेफी इनोव्हेशनवर विश्वास का ठेवावा",
    'section.trust.feat1.title': "अचूक अभियांत्रिकी",
    'section.trust.feat1.desc': "एरोस्पेस-ग्रेड सेन्सर आणि झिरो व्हेरिएशनसाठी सानुकूल थर्मल चेंबर्स.",
    'section.trust.feat2.title': "डेटा-आधारित थर्मल व्यवस्थापन",
    'section.trust.feat2.desc': "पूर्ण युनिटमध्ये 0.01°C अचूकता राखणारे सक्रिय फीडबॅक लूप.",
    'section.trust.feat3.title': "संस्थात्मक मानके",
    'section.trust.feat3.desc': "आंतरराष्ट्रीय बायोसेक्युरिटी आणि टिकाऊपणाच्या मानकांपेक्षा जास्त कामगिरीसाठी तयार.",
    'section.team.title': "आमचे नेतृत्व आणि भागीदार",
    'section.team.vidhya.title': "संस्थापक आणि सीईओ",
    'section.team.vidhya.desc': "सेरेसाठी धोरणात्मक दृष्टी आणि जैविक संशोधनाचे नेतृत्व. विद्या यांचे इनक्यूबेशन फिजिक्सवरील लक्ष हार्डवेअर विकासाचा पाया आहे.",
    'section.team.aditya.title': "सह-संस्थापक आणि सीटीओ",
    'section.team.aditya.desc': "तांत्रिक स्टॅक आणि सॉफ्टवेअर आर्किटेक्चरचे संचालन. आदित्य कृषी हार्डवेअरसाठी IoT एकत्रीकरणात तज्ञ आहेत.",
    'section.team.supported': "सहकार्य",
    'section.seretalks.title': "सेरे टॉक्स",
    'section.seretalks.subtitle': "आमच्या प्रवासातील काही खास गोष्टी",
    'section.gallery.title': "प्रत्यक्ष कार्य",
    'section.gallery.subtitle': "वास्तविक तैनाती, वास्तविक प्रभाव.",
    'section.gallery.img1': "शेतात स्थानिक शेतकऱ्यांशी संवाद साधताना विद्या",
    'section.gallery.img2': "पोल्ट्री फार्म सेटअप",
    'section.gallery.img3': "हार्डवेअरवर चर्चा करताना टीम",
    'section.gallery.img4': "तंत्रज्ञान तैनाती",
    'slides.1.title': "हवामान अस्थिरता",
    'slides.1.desc': "नाजूक जैविक पर्यावरणास विस्कळीत करणारे बाह्य बदल.",
    'slides.2.title': "डेटा ब्लाइंडस्पॉट्स",
    'slides.2.desc': "रिअल-टाइममध्ये सूक्ष्म-थर्मल बदल ट्रॅक करण्यात अक्षमता.",
    'slides.3.title': "संसाधनांची नासाडी",
    'slides.3.desc': "पारंपारिक पद्धतींमुळे उत्पादनात अनिश्चितता आणि महसुलाचे नुकसान.",
    'section.interest.title': "रजिस्टर करा",
    'section.interest.desc': "तुमची जागा आजच आरक्षित करा.",
    'form.firstName': "पहिले नाव",
    'form.lastName': "आडनाव",
    'form.email': "ईमेल पत्ता",
    'form.phone': "फोन / व्हॉट्सअॅप",
    'form.city': "शहर / ठिकाण",
    'form.role': "मी एक...",
    'form.message': "संदेश (पर्यायी)",
    'form.submit': "रुचि नोंदवा",
    'form.consent': "मी सेरेफी टीमशी संपर्क साधण्यास संमती देतो.",
    'tech.title': "संस्थागत-ग्रेड हार्डवेअर",
    'tech.desc': "विश्वसनीयता आणि स्केलेबिलिटीसाठी अचूक-अभियांत्रिकी.",
    'tech.hero.badge': "प्रकाशित प्रयोगशाळा",
    'tech.hero.title': "परंपरा आणि अचूकतेचा संगम",
    'tech.hero.desc': "आम्ही सर्जिकल तंत्रज्ञान आणि सहानुभूतीपूर्ण डिझाइनद्वारे लहान कुक्कुटपालनाचे पुनरुज्जीवन करत आहोत.",
    'tech.hero.cta': "तंत्रज्ञान एक्सप्लोर करा",
    'tech.mission.badge': "आमचे ध्येय",
    'tech.mission.title': "सेंद्रिय अचूकता",
    'tech.mission.desc': "कृषी तंत्रज्ञान अनेकदा अल्पभूधारक शेतकऱ्यांना मागे सोडते. आमचा विश्वास आहे की नाविन्य केवळ मोठ्या उद्योगांसाठी नसावे.",
    'metrics.title': "अचूक पोल्ट्री ROI.",
    'metrics.desc': "पारंपारिक अंदाज ते स्वयंचलित अचूकतेपर्यंतच्या बदलाचा अनुभव घ्या.",
    'metrics.compare.title': "बाजार तुलना",
    'metrics.roi.title': "ROI इंटेलिजेंस",
    'contact.title': "अचूकतेबद्दल बोलूया.",
    'contact.desc': "तुम्ही तुमची हॅचरी अपग्रेड करण्यास तयार असाल किंवा आमच्या तंत्रज्ञानाबद्दल प्रश्न असतील, आमची टीम मदतीसाठी येथे आहे.",
    'contact.form.title': "संदेश पाठवा",
    'contact.form.submit': "संदेश पाठवा",
    'contact.form.sending': "पाठवत आहे...",
    'contact.success.title': "संदेश पाठवला!",
    'contact.success.desc': "संपर्क साधल्याबद्दल धन्यवाद. आमची टीम २४ तासांच्या आत तुमच्याशी संपर्क साधेल।",
    'wizard.step': "चरण",
    'wizard.of': "पैकी",
    'wizard.back': "मागे",
    'wizard.next': "पुढील",
    'wizard.submit': "सादर करा",
    'wizard.submitting': "सादर करत आहे...",
    'wizard.step1.title': "तुमची ओळख काय आहे?",
    'wizard.step1.desc': "तुमच्यासाठी अनुभव सानुकूलित करण्यात आम्हाला मदत करा.",
    'wizard.role.farmer': "शेतकरी",
    'wizard.role.farmer.desc': "वैयक्तिक किंवा अल्पभूधारक उत्पादक",
    'wizard.role.hobbyist': "छंद जोपासणारे",
    'wizard.role.hobbyist.desc': "उत्साही किंवा संशोधक",
    'wizard.role.investor': "गुंतवणूकदार / संस्था",
    'wizard.role.investor.desc': "व्यावसायिक स्तर किंवा निधी",
    'wizard.step2.capacity.title': "तुम्हाला किती क्षमतेची गरज आहे?",
    'wizard.step2.capacity.desc': "तुमच्या उद्दिष्टांना अनुरूप हार्डवेयर स्केल निवडा.",
    'wizard.step2.partnership.title': "कोणत्या प्रकारची भागीदारी?",
    'wizard.step2.partnership.desc': "तुमच्या ध्येयांशी सुसंगत क्षेत्र निवडा.",
    'wizard.partnership.strategic': "धोरणात्मक गुंतवणूक",
    'wizard.partnership.reseller': "वितरण / पुनर्विक्रेता",
    'wizard.partnership.institutional': "संस्थागत खरेदीदार",
    'wizard.partnership.other': "इतर भागीदारी",
    'wizard.step3.goal.title': "तुमचे प्राथमिक ध्येय काय आहे?",
    'wizard.step3.goal.desc': "आम्ही तुम्हाला यशस्वी होण्यासाठी कशी मदत करू शकतो हे समजून घेण्यास आम्हाला मदत करा.",
    'wizard.goal.hatch-rate': "हॅच रेट सुधारा",
    'wizard.goal.scale': "ऑपरेशन्स वाढवा",
    'wizard.goal.research': "संशोधन / विशेष पक्षी",
    'wizard.goal.first-time': "पहिल्यांदाच हॅचिंग",
    'wizard.step3.timeline.title': "तुमची वेळमर्यादा काय आहे?",
    'wizard.step3.timeline.desc': "तुम्ही कधी पुढे जाण्याचा विचार करत आहात?",
    'wizard.timeline.immediate': "त्वरीत (०-३ महिने)",
    'wizard.timeline.short': "अल्पकालीन (३-६ महिने)",
    'wizard.timeline.exploring': "सध्या फक्त पर्यायांचा शोध घेत आहे",
    'wizard.step4.title': "काही विशिष्ट आवश्यकता?",
    'wizard.step4.desc': "काही अतिरिक्त माहिती किंवा प्रश्न असल्यास कळवा (पर्यायी).",
    'wizard.step4.placeholder.investor': "आम्ही शोधत आहोत...",
    'wizard.step4.placeholder.farmer': "मी सध्या वेगळे मॉडेल वापरत आहे...",
    'wizard.step5.title': "अंतिम तपशील",
    'wizard.step5.desc': "आम्ही पुष्टीकरण कोठे पाठवावे?",
    'thanks.title': "धन्यवाद,",
    'thanks.desc': "तुमची आवड अधिकृतपणे नोंदवली गेली आहे. आमची टीम तुमच्या प्री-ऑर्डर आणि पुढील चरणांवर चर्चा करण्यासाठी लवकरच तुमच्याशी संपर्क साधेल.",
    'thanks.cta': "साइटवर परत जा",
    'legal.terms.title': "नियम आणि अटी",
    'legal.terms.content': "या वेबसाइटवर प्रवेश करून, आम्ही असे गृहीत धरतो की तुम्ही या नियम आणि अटी स्वीकारता. आपण या पृष्ठावर नमूद केलेल्या सर्व अटी आणि शर्तींशी सहमत नसल्यास सेरेफी इनोव्हेशन वापरणे सुरू ठेवू नका.",
    'legal.privacy.title': "गोपनीयता धोरण",
    'legal.privacy.content': "सेरेफी इनोव्हेशनमध्ये, आमच्या वेबसाइटवरून उपलब्ध, आमच्या मुख्य प्राधान्यांपैकी एक आमच्या अभ्यागतांची गोपनीयता आहे. या गोपनीयता धोरण दस्तऐवजात आमच्याद्वारे गोळा केलेली आणि रेकॉर्ड केलेली माहिती आणि आम्ही ती कशी वापरतो याचे प्रकार आहेत.",
    'legal.disclaimer.title': "अस्वीकरण",
    'legal.disclaimer.content': "या वेबसाइटवरील सर्व माहिती - सेरेफी इनोव्हेशन - चांगल्या विश्वासाने आणि केवळ सामान्य माहितीच्या उद्देशाने प्रकाशित केली आहे."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('English');

  useEffect(() => {
    const savedLang = localStorage.getItem('serefy-lang') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('serefy-lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || translations['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
